;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        hungry-delete-backward
        hungry-delete-forward
        indent-region
        kill-and-join-forward
        lua-electric-match
        org-force-self-insert
        org-indent-line
        org-return-indent
        org-self-insert-command
        phi-rectangle-next-line
        phi-rectangle-yank
        smart-end-of-line
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        align-current
        bc-set
        ibus-handle-event
        repeat
        smex
        ))
