;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        copy-line
        downcase-region
        electric-graphviz-dot-semi
        end-of-visual-line
        enh-ruby-electric-brace
        handle-switch-frame
        hungry-delete-backward
        hungry-delete-forward
        ido-switch-buffer
        increment-integer-at-point
        indent-for-tab-command
        indent-new-comment-line
        indent-region
        kill-and-join-forward
        lua-electric-match
        move-line-down
        move-line-up
        notes-dedent-or-delete
        org-force-self-insert
        org-indent-line
        org-return-indent
        org-self-insert-command
        orgtbl-ctrl-c-ctrl-c
        orgtbl-self-insert-command
        phi-rectangle-kill-region
        phi-rectangle-kill-ring-save
        phi-rectangle-next-line
        phi-rectangle-yank
        smart-beginning-of-line
        smart-end-of-line
        sp--self-insert-command
        sp-add-to-previous-sexp
        sp-beginning-of-sexp
        sp-end-of-sexp
        sp-remove-active-pair-overlay
        whole-line-or-region-comment-dwim-2
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        align-current
        bc-set
        down-list
        ibus-handle-event
        repeat
        smex
        ))
